name: cremation_app
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter


  fluttertoast: ^8.2.2  # You can try other versions if necessary
  url_launcher: ^6.3.1
  provider: ^6.1.1
  shared_preferences: ^2.2.2
  flutter_datetime_picker: ^1.5.1
  image_picker: ^1.1.2
  file_picker: ^9.2.2
  sign_in_with_apple: ^6.1.4
  flutter_dotenv: ^5.0.2
  http: ^1.3.0
  intl: ^0.20.2
  supabase_flutter: ^2.8.4
  photo_view: ^0.14.0
  flutter_pdfview: ^1.0.0
  path_provider: ^2.0.8
  open_file: ^3.0.0
  webview_flutter: ^4.0.0
  gotrue: ^2.11.1
  postgrest: ^2.4.1
  flutter_local_notifications: ^19.0.0
  uuid: ^4.5.1
  timezone: 0.10.0

dev_dependencies:
  flutter_launcher_icons: ^0.13.1

  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
flutter_icons:
  android: true
  ios: true
  image_path: "assets/logo.png"
  assets:
    adaptive_icon_foreground: "assets/logo.png"
